### ISSUE TITLE
Cant upload files

### ISSUE THREAD

**Issue by ethamitc** [minegamer5570/Filehub#3]
My issue has NOT been removed! Liam, DONT change this!

**Comment by minegamer5570** [comment]
Do u notice how the site is in beta and how there is a part of the site's intro that says to e-mail request to upload files to me.

**Comment by ethamitc** [comment]
Hello their ethamitc, we are updating the ReadMe Document with this information! Please check back in the next half hour.

**Comment by minegamer5570** [comment]
Ethan, You just commented on your own question. Please don't do this and rember to check over your facts before putting up an issue. There were instructions on how to do this on the site and you knew about this. Removing thread...

**Comment by ethamitc** [comment]
Ugh... why do u do this

**Comment by ethamitc** [comment]
#Issue Closed
This issue has been closed by the Up-Tech Development Team!

Ethan,
Up-Tech Development
Web Development & Ticket Management Team's
