### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by minegamer5570** [minegamer5570/Filehub#4]
# Bug report

Welcome to the bug report page. This issue thread allows contributors to report bugs and issues within filehub so that the appropriate action is taken to fix the bug. TIP: To get a faster response, please add @minegamer5570 or @ethamitc so that we will see it and acknowledge the bug faster.
_______________________________________________________________________________________________________________
Existing bugs: (If the bug is listed here, we are aware of it and we are fixing it.)
- No bugs here! Hooray!

Fixed bugs: (Bugs displayed here have been removed or fixed.)
- No bugs here! Hooray!

(Contributors are NOT to close this issue or else there will be consequences!)

**Comment by ethamitc** [comment]
This isn't how issues work, use a wiki page for this!

**Comment by ethamitc** [comment]
@minegamer5570,
     Why does this post have the Bug & Development Error labels, if it isnt a bug or a development error but instead A bug Report? I feel all the tags should be removed.)

**Comment by ethamitc** [comment]
# CLOSED FOR ABANDONMENT!
