### ISSUE TITLE
Un-needed Branch

### ISSUE THREAD

**Issue by ethamitc** [minegamer5570/Filehub#6]
@minegamer5570,

The branch, Ethan is not needed. We need to remove it. Great if you could do this.

Edited by @minegamer5570 on 9:54 AM 11/10/2017

**Comment by minegamer5570** [comment]
Thanks for telling us about this. We will remove it as soon as possible.


[This thread has been closed by @minegamer5570 for the reason: Issue has been answered and is no longer needed. at 9:57 AM on 11/10/2017.]

**Comment by minegamer5570** [comment]
# Issue Closed
This issue has been closed by the *Up-Tech Development Team*!

Ethan,
Up-Tech Development
Web Development & Ticket Management Team's
