### ISSUE TITLE
File Backup

### ISSUE THREAD

**Issue by ethamitc** [minegamer5570/Filehub#7]
@minegamer5570,
      What if we created an account on a cloud storage site (I'll tell you it later to not advertise it), and then uploaded a backup of all the user-files.

**Comment by minegamer5570** [comment]
# R.E: File Backup (#7)

### Thanks for the idea

Most of the files for the site including user files will be stored on a
separate file server for different reasons so this sort of system is
already being made. But this is a great idea!

Liam,
Up-Tech Development
CEO and Founder of Up-Tech Development.

**Comment by minegamer5570** [comment]
# Issue Closed
This issue has been closed by the *Up-Tech Development Team*!

Liam,
Up-Tech Development
CEO and Founder of Up-Tech Development.
