### ISSUE TITLE
Removal of Branch

### ISSUE THREAD

**Issue by ethamitc** [minegamer5570/Filehub#8]
@minegamer5570 
Can you please remove the branch ethamitc_edit1. Its no longer needed!

**Comment by minegamer5570** [comment]
Thanks for letting us know!

[ Thank you for telling us about this! We have ]
[ removed the branch from the project. Sorry   ]
[ the delay.                                                        ]

Posed by Liam Hogan (Owner).

**Comment by minegamer5570** [comment]
# Issue Closed
This issue has been closed by the *Up-Tech Development Team*!

Liam,
Up-Tech Development
CEO and Founder of Up-Tech Development.
